<?php
namespace Phpmig\Test\Adapter\File;

use \Phpmig\Adapter\File\Flat;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-08 at 14:04:35.
 */
class FlatTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Flat
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Flat(__DIR__.'/good.log');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phpmig\Adapter\File\Flat::fetchAll
     * @todo   Implement testFetchAll().
     */
    public function testFetchAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phpmig\Adapter\File\Flat::up
     * @todo   Implement testUp().
     */
    public function testUp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phpmig\Adapter\File\Flat::down
     * @todo   Implement testDown().
     */
    public function testDown()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phpmig\Adapter\File\Flat::hasSchema
     * @todo   Implement testHasSchema().
     */
    public function testHasSchema()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phpmig\Adapter\File\Flat::createSchema
     * @todo   Implement testCreateSchema().
     */
    public function testCreateSchema()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
